import fs from 'fs/promises';
import path from 'path';
import AdmZip from 'adm-zip';
import { getProject } from './projects';

export async function createExportZip(projectId: string): Promise<Buffer> {
    const project = await getProject(projectId);
    if (!project) throw new Error('Project not found');

    const projectDir = path.join(process.cwd(), 'projects', projectId);
    const trainDataDir = path.join(projectDir, 'train_data');

    // Check if train_data/ exists
    try {
        await fs.access(trainDataDir);
    } catch {
        throw new Error('train_data folder not found. Please run captioning first to generate the training dataset.');
    }

    const zip = new AdmZip();

    // Read all files from train_data/
    const files = await fs.readdir(trainDataDir);

    let imagesExported = 0;
    let captionsExported = 0;

    // Separate images and captions
    const imageFiles = files.filter(f => /\.(jpg|jpeg|png|webp)$/i.test(f));
    const captionFiles = files.filter(f => f.endsWith('.txt'));

    // Add images
    for (const imageFile of imageFiles) {
        const filePath = path.join(trainDataDir, imageFile);
        const fileBuffer = await fs.readFile(filePath);
        zip.addFile(`dataset/images/${imageFile}`, fileBuffer);
        imagesExported++;
    }

    // Add captions
    for (const captionFile of captionFiles) {
        const filePath = path.join(trainDataDir, captionFile);
        const fileBuffer = await fs.readFile(filePath);
        zip.addFile(`dataset/captions/${captionFile}`, fileBuffer);
        captionsExported++;
    }

    // Add export metadata
    zip.addFile('export_map.json', Buffer.from(JSON.stringify({
        projectId: project.id,
        projectName: project.name,
        exportedAt: new Date().toISOString(),
        imagesExported,
        captionsExported,
        source: 'train_data'
    }, null, 2), 'utf-8'));

    // Add README
    const readmeContent = `
# Dataset: ${project.name}

Generated by LoRA Bento.

## Stats
- Total Images: ${imagesExported}
- Total Captions: ${captionsExported}
- Source: train_data/ (captioned dataset)

## Configuration
- Trigger Word: ${project.settings?.triggerWord || 'None'}
- Caption Model: ${project.settings?.captionModel || 'Manual/Imported'}

## Training Instructions
1. This dataset is structured for Kohya-ss, OneTrainer, and FluxGym.
2. Point your trainer to the \`dataset\` folder (contains images/ and captions/ subdirectories).
3. Use the trigger word "${project.settings?.triggerWord || ''}" in your prompts if applicable.

## Structure
- \`dataset/images/\` - Training images
- \`dataset/captions/\` - Caption files matching image basenames
  `.trim();

    zip.addFile('README.md', Buffer.from(readmeContent, 'utf-8'));

    console.log(`Exported project ${projectId} from train_data/: ${imagesExported} images, ${captionsExported} captions.`);

    return zip.toBuffer();
}
