import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SettingsProvider } from "@/components/settings/settings-provider";
import { SettingsModal } from "@/components/settings/settings-modal";
import { OnboardingGate } from "@/components/onboarding/onboarding-gate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased connection-monitor`}
      >
        <SettingsProvider>
          <OnboardingGate>
            {children}
            <SettingsModal />
          </OnboardingGate>
        </SettingsProvider>
      </body>
    </html>
  );
}
