import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SettingsProvider } from "@/components/settings/settings-provider";
import { SettingsModal } from "@/components/settings/settings-modal";
import { OnboardingGate } from "@/components/onboarding/onboarding-gate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased connection-monitor`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var savedTheme = localStorage.getItem('theme') || 'light';
                  var root = document.documentElement;
                  root.classList.remove('dark');
                  root.removeAttribute('data-theme');
                  
                  if (savedTheme === 'dark') {
                    root.classList.add('dark');
                    root.style.colorScheme = 'dark';
                    root.dataset.theme = 'dark';
                  } else if (savedTheme === 'gockso') {
                    root.setAttribute('data-theme', 'gockso');
                    root.style.colorScheme = 'light';
                    root.dataset.theme = 'gockso';
                  } else {
                    root.style.colorScheme = 'light';
                    root.dataset.theme = 'light';
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
        <SettingsProvider>
          <OnboardingGate>
            {children}
            <SettingsModal />
          </OnboardingGate>
        </SettingsProvider>
      </body>
    </html>
  );
}
